# Generated by Django 2.1 on 2022-03-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200815_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_like_counts',
            field=models.BooleanField(default=False),
        ),
    ]
