# Generated by Django 2.1 on 2022-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_hide_like_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_like_counts',
            field=models.BooleanField(default=True),
        ),
    ]
