# Generated by Django 2.1 on 2022-03-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220325_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_like_counts',
            field=models.BooleanField(default=False),
        ),
    ]
