on:
  pull_request:
    branches: 
      - master 
      - develop 
jobs:
  request-reviewa:
    name: Requesting reviews
    runs-on: ubuntu-latest
    steps:
      - name: Request reviews from everyone
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          config: .github/reviewers.yml # Config file location override
